# Cars I'm Considering
### January 2022

_____
## What is this?
> #### I recently found out that my car has been deemed a total loss after a car accident, and my insurance company has offered me a settlement. Using only the money from the settlement, I will be getting another car. I already had a google sheet to keep track of the cars I thought looked good, so I thought I might as well make it a dataframe to look even better. Below are the dataframes, one with the car info and one with the clickable links that have corresponding index numbers for reference on the left side of the dataframes.

In [41]:
import pandas as pd

# url of google sheet 
sheet_url = 'https://docs.google.com/spreadsheets/d/10aR5gtRwn4h-Nf9FmV3NULUs5-qqdN5v-jN1glzT6Dg/edit#gid=0'    

# turn that url into a CSV export URL: Replace /edit with /export; 
# add format=csv to the beginning of the query string.
csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

# pass it to pd.read_csv, which can take a URL.
df = pd.read_csv(csv_export_url)

In [45]:
from IPython.core.display import display, HTML
import pandas as pd


links = pd.DataFrame({"url": ['https://www.carzoftexas.net/details/used-2008-nissan-altima/78522354',
'https://www.cjautosalesllc.com/details/new-2009-honda-accord/66718173',
'https://www.rubensautosalesllc.net/vehicle/used-2007-nissan-murano-s-4115822', 
'https://www.cjautosalesllc.com/details/used-2008-honda-pilot/82026312', 
'https://www.cjautosalesllc.com/details/new-2014-nissan-sentra/79217637',
'https://www.cjautosalesllc.com/details/new-2011-nissan-altima/71089748', 
'https://www.cjautosalesllc.com/details/new-2008-nissan-altima/75774865', 
'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=612592080&maxPrice=5000&priceRange=&LNX=SPGOOGLENONBRANDBODYSTYLE&utm_source=GOOGLE&utm_medium=sem_non-brand_perf&utm_campaign=at_na_na_evergreen_na_roi_na_na&utm_content=na_na_na_na_na_spgooglenonbrandbodystyle_na&utm_term=used%20cars%20under%205000&gclid=Cj0KCQiA8vSOBhCkARIsAGdp6RQ5sdZUsWg7uZUUc2EVwFT3UHHzbPGsAlaHb-OOzPypL-g35US42bsaArGIEALw_wcB&gclsrc=aw.ds&zip=78201&state=TX&city=San%20Antonio&dma=&searchRadius=50&listingTypes=USED&isNewSearch=false&referrer=%2Fcars-for-sale%2Fcars-under-5000%3FLNX%3DSPGOOGLENONBRANDBODYSTYLE%26utm_source%3DGOOGLE%26utm_medium%3Dsem_non-brand_perf%26utm_campaign%3Dat_na_na_evergreen_na_roi_na_na%26utm_content%3Dna_na_na_na_na_spgooglenonbrandbodystyle_na%26utm_term%3Dused%2520cars%2520under%25205000%26gclid%3DCj0KCQiA8vSOBhCkARIsAGdp6RQ5sdZUsWg7uZUUc2EVwFT3UHHzbPGsAlaHb-OOzPypL-g35US42bsaArGIEALw_wcB%26gclsrc%3Daw.ds&clickType=listing',
'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=602006595&zip=78201&referrer=%2Fcars-for-sale%2Fsearchresults.xhtml%3Fzip%3D78201%26city%3DSan%2BAntonio%26incremental%3Dall%26listingTypes%3DUSED%26LNX%3DSPGOOGLENONBRANDBODYSTYLE%26sortBy%3Drelevance%26maxPrice%3D5000%26state%3DTX%26searchByDma%3Dfalse%26firstRecord%3D0%26marketExtension%3Dinclude%26relevanceConfig%3Drelevance-v2%26searchRadius%3D50%26isNewSearch%3Dfalse&listingTypes=USED&numRecords=25&maxPrice=5000&searchByDma=false&firstRecord=0&searchRadius=50&makeCode1=HONDA&modelCode1=ACCORD&clickType=listing',
'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=623229570&zip=78201&referrer=%2Fcars-for-sale%2Fsearchresults.xhtml%3Fzip%3D78201%26city%3DSan%2BAntonio%26incremental%3Dall%26listingTypes%3DUSED%26LNX%3DSPGOOGLENONBRANDBODYSTYLE%26sortBy%3Drelevance%26location%3D%255Bobject%2BObject%255D%26maxPrice%3D5000%26state%3DTX%26searchByDma%3Dfalse%26firstRecord%3D50%26marketExtension%3Dinclude%26relevanceConfig%3Drelevance-v2%26searchRadius%3D50%26isNewSearch%3Dfalse&listingTypes=USED&numRecords=25&maxPrice=5000&searchByDma=false&firstRecord=50&searchRadius=50&makeCode1=TOYOTA&modelCode1=CAMRY&clickType=listing',
'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=614188231&zip=78201&referrer=%2Fcars-for-sale%2Fsearchresults.xhtml%3Fzip%3D78201%26city%3DSan%2BAntonio%26incremental%3Dall%26listingTypes%3DUSED%26LNX%3DSPGOOGLENONBRANDBODYSTYLE%26sortBy%3Drelevance%26location%3D%255Bobject%2BObject%255D%26maxPrice%3D5000%26state%3DTX%26searchByDma%3Dfalse%26firstRecord%3D50%26marketExtension%3Dinclude%26relevanceConfig%3Drelevance-v2%26searchRadius%3D50%26isNewSearch%3Dfalse&listingTypes=USED&numRecords=25&maxPrice=5000&searchByDma=false&firstRecord=50&searchRadius=50&makeCode1=AUDI&modelCode1=A4&clickType=listing', 
'https://www.edmunds.com/jeep/compass/2007/vin/1J8FT47W67D171463/?radius=50',
'https://www.carzing.com/car/tx/san-antonio/2009-jeep-liberty-limited-edition-sport-utility-4d/715c2742-4c4a-ec11-a125-005056968156?search=jeep&minPrice=500&maxPrice=5500&minMileage=0&maxMileage=175000&sort=PH',
'https://www.carzing.com/car/tx/san-antonio/2008-volkswagen-jetta-se-sedan-4d/7288b4a3-4854-ec11-a125-005056968156?minPrice=500&maxPrice=5500&dealerid=bbf5bf7b2f0457204a5826b707083a1c']})


links['Working_Links'] = links.apply(lambda row: "<a href='{}' target='_blank'>{}</a>".format(row.url, row.url.split("/")[2]), axis=1)

del df['Link']

In [46]:
tables = (df, display(HTML(links[["Working_Links"]].to_html(escape=False))))
pd.concat(tables)

,Price,Year,Color,Make,Model,Notes/features/mileage
0,$4.5k,2008,Red,Nissan,Altima Coupe,"173,209 miles"
1,$4.2k,2009,Black,Honda,Accord EX-L,"Poor condition on the inside, Navigation System"
2,$3.9k,2007,Silver,Nissan,Murano,"196,288 miles, AWD, Navigation System"
3,$4.9k,2008,Black,Honda,Pilot,"180,021 miles"
4,$4.9k,2014,Dark Grey,Nissan,Sentra,Very good condition
5,$4.9k,2011,Grey,Nissan,Altima,Good condition
6,$3.9k,2008,Black,Nissan,Altima Coupe,"138,001 miles, really nice - black leather int..."
7,$4.5k,2009,Silver,Chevy,Equinox,"133,838 miles"
8,$4.6k,2008,Silver,Honda,Accord,"211,163 miles, good condition, black leather s..."
9,$4.9k,2007,Red,Toyota,Camry SE,"134,910 miles, no pictures"
10,$4.5k,2007,Silver,Audi,A4,"150,000 miles, turbo engine"
11,$4.5k,2007,Gold,Jeep,Compass Sport,"165,257 miles"
12,$4.1k,2009,Red,Jeep,Liberty Limited,"148,115 miles"
13,$4.9k,2008,Black,Volkswagen,Jetta SE,"129,255 miles"